###
POST http://localhost:5000/api/register/ HTTP/1.1 
Content-Type: application/json

{
"name" : "test", 
"email": "test@foo.com",
"password": "A12345"
}

###
POST http://localhost:5000/api/login/ HTTP/1.1 
Content-Type: application/json

{
"email": "test@foo.com",
"password": "A12345"
}

###
POST http://localhost:5000/api/logout/ HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidG9rZW5fdmVyc2lvbiI6MCwiaWF0IjoxNzMzNDUwNDg5LCJleHAiOjE3MzM0NTA1NDl9.YGt_85kNkLR04uKLX-TkUI0CBCQvuC68XvIvd1YWyRw

{
"email": "test@foo.com",
"password": "A12345"
}

###
DELETE http://localhost:5000/api/auth/account/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidG9rZW5fdmVyc2lvbiI6MCwiaWF0IjoxNzMzNDUxMTIwLCJleHAiOjE3MzM0NTExODB9.MFdcuaoWHNXCMDRJzRyiCuETVTmprvcyIupqqWLHtfk

###
GET http://localhost:5000/api/groups/1 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/api/groups/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzMzMzkwMzQxfQ.uVuCoFhfCGNFlmJgmCYPtm_tbqW-7OIqcqfYN-O2oXo

{
  "name": "Testing Group",
  "description": "This is a testing group from backend"
}

###
POST http://localhost:5000/api/reviews/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzMzNDQ0NjcyfQ.mWTqYCHPf3mr8W75ppkdVK7SQ6j6gGGIgpE4szDnmB0

{
  "movieId": 1035048,
  "description": "Try to send a review",
  "rating": 4
}
